version: '3.8'

services:
  model-repo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hugging-face-model-repo
    ports:
      - "8900:8900"
    volumes:
      - /localModelRepo:/app/models
    environment:
      - NODE_ENV=production
      - PORT=8900
      - HOST=0.0.0.0
      - MODELS_DIR=/app/models
    restart: unless-stopped
    platform: linux/arm64

